const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./ice-cream/index.js', './cookies/index.js'],
    basePath: '/',
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        description: 'Test API with autogenerated swagger doc',
        swagger: '2.0',
        title: 'Dessert API',
        version: '1.0.0',
      },
    },
};

const specs = swaggerJsdoc(options);
export default specs;
